name: Github-Automation



on: 
  push:
    branches: 
      - branch_terraform

  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:  
  
    - name: update github repo secrets
      run: |
          echo ${{ secrets.Test_secret }}
        
