name: Github-Automation



on: 
  push:
    branches: 
      - main

  
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:  
    

    - name: Step 6 - Intall CF-CLI
      run: |
      
         curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | tar -zx
          # ...move it (and the "cf" symlink which points to it) to /usr/local/bin or a location you know is in your $PATH
          mv cf8 /user/local/bin
          mv cf /usr/local/bin
          # ...copy tab completion file on Ubuntu (takes affect after re-opening your shell)
          sudo curl -o /usr/share/bash-completion/completions/cf8 https://raw.githubusercontent.com/cloudfoundry/cli-ci/master/ci/installers/completion/cf8
          # ...and to confirm your cf CLI version
          cf version
  
#     - name: update github repo secrets
#       run: |
#            curl -u Ramya-ravindra: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  https://api.github.com/repos/practice-test-organisation/test-repo-api2/actions/secrets
#           # curl -X PUT -H "Authorization: token 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" -H "Content-Type: application/json" -i https://api.github.com/repos/practice-test-organisation/test-repo-api2/actions/secrets/CACHIX_SIGNING_KEY -d '{"key_id": "568250167242549743", "encrypted_value": "$ENCRYPTED_CACHIX_SIGNING_KEY"}'
#           # curl -u Ramya-ravindra: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  https://api.github.com/orgs/practice-test-organisation/actions/secrets/keyvalue  -d '{"visibility":"selected"}'
#              # curl -u Ramya-ravindra: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  https://api.github.com/orgs/practice-test-organisation/actions/secrets/XYZ/repositories
#             #  curl -u Ramya-ravindra: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  https://api.github.com/orgs/practice-test-organisation/actions/secrets/CACHIX_SIGNING_KEY -d '{"key_id": "568250167242549743", "encrypted_value": "$ENCRYPTED_CACHIX_SIGNING_KEY"}'
#              #curl -u Ramya-ravindra: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   https://api.github.com/orgs/practice-test-organisation/actions/secrets/public-key
#             #curl -u Ramya-ravindra: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  https://api.github.com/orgs/practice-test-organisation/actions/secrets
#             # curl -u Ramya-ravindra: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 https://api.github.com/orgs/practice-test-organisation/repos -d '{"name":"test-repo-api2"}'
        
        
        
